DROP DATABASE IF EXISTS springmvcdemos;
CREATE DATABASE springmvcdemos; 
USE springmvcdemos;

DROP TABLE if exists CARSERVICE CASCADE;
DROP TABLE if exists PARTS CASCADE;



CREATE TABLE PARTS(
  PARTID Integer(11) ,
  PARTNAME VARCHAR(10) NOT NULL,
  PRICE DOUBLE ,
  CARTYPE VARCHAR(10) NOT NULL,
  CONSTRAINT PARTS_PK PRIMARY KEY (PARTID)
);

CREATE TABLE CARSERVICE(
 SERVICEID Integer AUTO_INCREMENT,
 CARTYPE VARCHAR(10),
 CARNUMBER VARCHAR(11),
 PARTID Integer(11),
 USERNAME VARCHAR(10),
 TOTALREPAIRCOST Integer(10),
 CONSTRAINT CARSERVICE_PK PRIMARY KEY(SERVICEID),
 CONSTRAINT CARSERVICE_FK FOREIGN KEY(PARTID) REFERENCES PARTS(PARTID)
);


INSERT INTO PARTS VALUES (1001, 'BRAKE',   900, 'MARUTI');
INSERT INTO PARTS VALUES (1002, 'TYRE',   400, 'MARUTI');
INSERT INTO PARTS VALUES (1003, 'BRAKE',   1000, 'HYUNDAI');
INSERT INTO PARTS VALUES (1004, 'TYRE',   600, 'HYUNDAI');
INSERT INTO PARTS VALUES (1005, 'WIPER',   700, 'HYUNDAI');
INSERT INTO PARTS VALUES (1006, 'WIPER',   800, 'MARUTI');
INSERT INTO PARTS VALUES (1008, 'GEAR',   1500, 'HYUNDAI');
commit;
DROP DATABASE IF EXISTS springmvcdemos;
CREATE DATABASE springmvcdemos; 
USE springmvcdemos;

DROP TABLE if exists CARSERVICE CASCADE;
DROP TABLE if exists PARTS CASCADE;



CREATE TABLE PARTS(
  PARTID Integer(11) ,
  PARTNAME VARCHAR(10) NOT NULL,
  PRICE DOUBLE ,
  CARTYPE VARCHAR(10) NOT NULL,
  CONSTRAINT PARTS_PK PRIMARY KEY (PARTID)
);

CREATE TABLE CARSERVICE(
 SERVICEID Integer AUTO_INCREMENT,
 CARTYPE VARCHAR(10),
 CARNUMBER VARCHAR(11),
 PARTID Integer(11),
 USERNAME VARCHAR(10),
 TOTALREPAIRCOST Integer(10),
 CONSTRAINT CARSERVICE_PK PRIMARY KEY(SERVICEID),
 CONSTRAINT CARSERVICE_FK FOREIGN KEY(PARTID) REFERENCES PARTS(PARTID)
);


INSERT INTO PARTS VALUES (1001, 'BRAKE',   900, 'MARUTI');
INSERT INTO PARTS VALUES (1002, 'TYRE',   400, 'MARUTI');
INSERT INTO PARTS VALUES (1003, 'BRAKE',   1000, 'HYUNDAI');
INSERT INTO PARTS VALUES (1004, 'TYRE',   600, 'HYUNDAI');
INSERT INTO PARTS VALUES (1005, 'WIPER',   700, 'HYUNDAI');
INSERT INTO PARTS VALUES (1006, 'WIPER',   800, 'MARUTI');
INSERT INTO PARTS VALUES (1008, 'GEAR',   1500, 'HYUNDAI');
commit;










